export const ADD_POST = "PROFILE/ADD-POST";
export const UPDATE_NEW_POST_TEXT = 'PROFILE/UPDATE-NEW-POST-TEXT';
export const ADD_MESSAGE = "DIALOGS/ADD-MESSAGE";
export const UPDATE_NEW_MESSAGE = "DIALOGS/UPDATE-NEW-POST-MESSAGE";
