export const ADD_POST = "PROFILE/ADD-POST";

export const ADD_MESSAGE = "DIALOGS/ADD-MESSAGE";

export const FOLLOW = "USERS/FOLLOW";
export const UN_FOLLOW = "USERS/UN-FOLLOW";
export const SET_USERS = "USERS/SET-USERS";
export const SET_STATUS = "USERS/SET-STATUS";
export const SET_CURRENT_PAGE = "USERS/SET-CURRENT-PAGE";
export const SET_TOTAL_USER_COUNT = "USERS/SET-TOTAL-USER-COUNT";
export const SET_USER_PROFILE = "USERS/SET-USER-PROFILE";
export const TOGGLE_IS_FETCHING = "USERS/TOGGLE-IS-FETCHING";
export const TOGGLE_IS_FOLLOWING_PROGRESS = "USERS/TOGGLE-IS-FOLLOWING-PROGRESS";

export const SET_USER_DATA = "AUTH/SET-USER-DATA";
